'use client';

import { Title, Container, Text } from '@mantine/core';
import classes from './PrivacyPage.module.css';

export function PrivacyPage() {
  return (
    <div className={classes.outer}>
      <Container size="lg">
        <Title className={classes.mainTitle} order={1}>
          Privacy Policy
        </Title>
        <div>
          <Text className={classes.text}>
            This Privacy Policy describes Our policies and procedures on the collection, use and
            disclosure of Your information when You respond to our advertisements and tells You
            about Your privacy rights and how the law protects You. We use Your Personal Data to
            contact and support you, as well as to provide and improve the Service. By using the
            Service, You agree to the collection and use of information in accordance with this
            Privacy Policy.
          </Text>
          <Title order={2} className={classes.secondaryTitle}>Interpretation and Definitions</Title>
          <Title order={3} className={classes.tercaryTitle}>Interpretation</Title>
          <Text className={classes.text}>
            The words of which the initial letter is capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless
            of whether they appear in singular or in plural.
          </Text>
          <Title order={3} className={classes.tercaryTitle}>Definitions</Title>
          <Text className={classes.text}>For the purposes of this Privacy Policy:</Text>
          <Text className={classes.text}>
            Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
            refers to Ezclick.
          </Text>
          <Text className={classes.text}>
            Device means any device that can access the Service such as a computer, a cellphone or a
            digital tablet.
          </Text>
          <Text className={classes.text}>
            Personal Data is any information that relates to an identified or identifiable
            individual.
          </Text>
          <Text className={classes.text}>Service refers to the advertisement, website, or application.</Text>
          <Text className={classes.text}>
            Service Provider means any natural or legal person who processes the data on behalf of
            the Company. It refers to other companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the Company, to perform
            services related to the Service or to assist the Company in analyzing how the Service is
            used.
          </Text>
          <Text className={classes.text}>
            Usage Data refers to data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself (for example, the duration of a page
            visit).
          </Text>
          <Text className={classes.text}>
            You means the individual accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the Service, as
            applicable.
          </Text>
          <Title order={2} className={classes.secondaryTitle}>Collecting and Using Your Personal Data</Title>
          <Title order={3} className={classes.tercaryTitle}>Types of Data Collected</Title>
          <Text className={classes.text}>
            While using Our Service, We may ask You to provide Us with certain personally
            identifiable information that can be used to contact or identify You. Personally
            identifiable information may include, but is not limited to:
          </Text>
          <Text className={classes.text}>First and last name</Text>
          <Text className={classes.text}>Email address</Text>
          <Text className={classes.text}>Phone number</Text>
          <Text className={classes.text}>Location details such as your address, city or country</Text>
          <Text className={classes.text}>Any other data such as personal preferences, requirements or comments</Text>
          <Title order={3} className={classes.tercaryTitle}>Use of Your Personal Data</Title>
          <Text className={classes.text}>The Company may use Personal Data for the following purposes:</Text>
          <Text className={classes.text}>
            To provide and maintain our Service , including to monitor the usage of our Service.
          </Text>
          <Text className={classes.text}>
            To manage Your Account: to manage Your registration as a user of the Service. The
            Personal Data You provide can give You access to different functionalities of the
            Service that are available to You as a registered user.
          </Text>
          <Text className={classes.text}>
            For the performance of a contract: the development, compliance and undertaking of the
            purchase contract for the products, items or services You have purchased or of any other
            contract with Us through the Service.
          </Text>
          <Text className={classes.text}>
            To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms
            of electronic communication, such as a mobile application's push notifications regarding
            updates or informative communications related to the functionalities, products or
            contracted services, including the security updates, when necessary or reasonable for
            their implementation.
          </Text>
          <Text className={classes.text}>
            To provide You with news, special offers and general information about other goods,
            services and events which we offer that are similar to those that you have already
            purchased or enquired about unless You have opted not to receive such information.
          </Text>
          <Text className={classes.text}>To manage Your requests: To attend and manage Your requests to Us.</Text>
          <Text className={classes.text}>
            For business transfers: We may use Your information to evaluate or conduct a merger,
            divestiture, restructuring, reorganization, dissolution, or other sale or transfer of
            some or all of Our assets, whether as a going concern or as part of bankruptcy,
            liquidation, or similar proceeding, in which Personal Data held by Us about our Service
            users is among the assets transferred.
          </Text>
          <Text className={classes.text}>
            For other purposes: We may use Your information for other purposes, such as data
            analysis, identifying usage trends, determining the effectiveness of our promotional
            campaigns and to evaluate and improve our Service, products, services, marketing and
            your experience.
          </Text>
          <Text className={classes.text}>We may share Your personal information in the following situations:</Text>
          <Text className={classes.text}>
            With Service Providers: We may share Your personal information with Service Providers to
            monitor and analyze the use of our Service, to contact You.
          </Text>
          <Text className={classes.text}>
            For business transfers: We may share or transfer Your personal information in connection
            with, or during negotiations of, any merger, sale of Company assets, financing, or
            acquisition of all or a portion of Our business to another company.
          </Text>
          <Text className={classes.text}>
            With Your consent: We may disclose Your personal information for any other purpose with
            Your consent.
          </Text>
          <Title order={3} className={classes.tercaryTitle}>Retention of Your Personal Data</Title>
          <Text className={classes.text}>
            The Company will retain Your Personal Data only for as long as is necessary for the
            purposes set out in this Privacy Policy. We will retain and use Your Personal Data to
            the extent necessary to comply with our legal obligations (for example, if we are
            required to retain your data to comply with applicable laws), resolve disputes, and
            enforce our legal agreements and policies.
          </Text>
          <Text className={classes.text}>The Company will also retain Usage Data for internal analysis purposes.</Text>
          <Title order={3} className={classes.tercaryTitle}>Transfer of Your Personal Data</Title>
          <Text className={classes.text}>
            Your information, including Personal Data, is processed at the Company's operating
            offices and in any other places where the parties involved in the processing are
            located. It means that this information may be transferred to — and maintained on —
            computers located outside of Your state, province, country or other governmental
            jurisdiction where the data protection laws may differ than those from Your
            jurisdiction.
          </Text>
          <Text className={classes.text}>
            Your consent to this Privacy Policy followed by Your submission of such information
            represents Your agreement to that transfer.
          </Text>
          <Text className={classes.text}>
            The Company will take all steps reasonably necessary to ensure that Your data is treated
            securely and in accordance with this Privacy Policy and no transfer of Your Personal
            Data will take place to an organization or a country unless there are adequate controls
            in place including the security of Your data and other personal information.
          </Text>
          <Title order={3} className={classes.tercaryTitle}>Disclosure of Your Personal Data</Title>
          <Title order={4}>Law enforcement</Title>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if
          required to do so by law or in response to valid requests by public authorities (e.g. a
          court or a government agency).
          <Title order={4}>Other legal requirements</Title>
          <Text className={classes.text}>
            The Company may disclose Your Personal Data in the good faith belief that such action is
            necessary to:
          </Text>
          <Text className={classes.text}>Comply with a legal obligation</Text>
          <Text className={classes.text}>Protect and defend the rights or property of the Company</Text>
          <Text className={classes.text}>Prevent or investigate possible wrongdoing in connection with the Service</Text>
          <Text className={classes.text}>Protect the personal safety of Users of the Service or the public</Text>
          <Text className={classes.text}>Protect against legal liability</Text>
          <Title order={3} className={classes.tercaryTitle}>Security of Your Personal Data</Title>
          <Text className={classes.text}>
            The security of Your Personal Data is important to Us, but remember that no method of
            transmission over the Internet, or method of electronic storage is 100% secure. While We
            strive to use commercially acceptable means to protect Your Personal Data, We cannot
            guarantee its absolute security.
          </Text>
          <Title order={2} className={classes.secondaryTitle}>Links to Other Websites</Title>
          <Text className={classes.text}>
            Our Service may contain links to other websites that are not operated by Us. If You
            click on a third party link, You will be directed to that third party's site. We
            strongly advise You to review the Privacy Policy of every site You visit.
          </Text>
          <Text className={classes.text}>
            We have no control over and assume no responsibility for the content, privacy policies
            or practices of any third party sites or services.
          </Text>
          <Title order={2} className={classes.secondaryTitle}>Changes to this Privacy Policy</Title>
          <Text className={classes.text}>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by
            posting the new Privacy Policy on this page.
          </Text>
          <Text className={classes.text}>
            You are advised to review this Privacy Policy periodically for any changes. Changes to
            this Privacy Policy are effective when they are posted on this page.
          </Text>
          <Text className={classes.text}>This Privacy Policy was last updated on 2024/04/03 13:02:11</Text>
          <Title order={2} className={classes.secondaryTitle}>Contact Us</Title>
          <Text className={classes.text}>
            If you have any questions about this Privacy Policy, You can contact us via email at
            support@ezclick.io
          </Text>
        </div>
      </Container>
    </div>
  );
}
